generator: generator.cpp
	g++ -Wall -g generator.cpp -o generator

generatorFixedHash: generatorFixedHash.cpp
	g++ -Wall -g generatorFixedHash.cpp -o generatorFixedHash

generator2mtf: generator2mtf.cpp
	g++ -Wall -g generator2mtf.cpp -o generator2mtf

randGenerator: randGenerator.cpp
	g++ -Wall -g randGenerator.cpp -o randGenerator

clean:
	rm -f generator
	rm -fr generator.dSYM/*
	rmdir generator.dSYM
