generator: generator.cpp
	g++ -Wall -g generator.cpp -o generator

randGenerator: randGenerator.cpp
	g++ -Wall -g randGenerator.cpp -o randGenerator

clean:
	rm -f generator
	rm -fr generator.dSYM/*
	rmdir generator.dSYM
