generator: generator.cpp
	g++ -Wall -g generator.cpp -o generator

generatorFixedHash: generatorFixedHash.cpp
	g++ -Wall -g generatorFixedHash.cpp -o generatorFixedHash

generatorBST: generatorBST.cpp
	g++ -Wall -g generatorBST.cpp -o generatorBST
generatorBSTgood: generatorBSTgood.cpp
	g++ -Wall -g generatorBSTgood.cpp -o generatorBSTgood
	
generator2mtf: generator2mtf.cpp
	g++ -Wall -g generator2mtf.cpp -o generator2mtf
generatorSplay: generatorSplay.cpp
	g++ -Wall -g generatorSplay.cpp -o generatorSplay

randGenerator: randGenerator.cpp
	g++ -Wall -g randGenerator.cpp -o randGenerator

clean:
	rm -f generator
	rm -fr generator.dSYM/*
	rmdir generator.dSYM
